// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoLl5anSucBNbgFojzNkJZuma_LAj95Co',
    appId: '1:967804782333:android:bf4b9f87b35e1941722094',
    messagingSenderId: '967804782333',
    projectId: 'project1-8606d',
    storageBucket: 'project1-8606d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBckNpKgBIgB_c5LgrvcBu0xCogXCj_-nc',
    appId: '1:967804782333:ios:f51e3b5b3e991b61722094',
    messagingSenderId: '967804782333',
    projectId: 'project1-8606d',
    storageBucket: 'project1-8606d.appspot.com',
    androidClientId: '967804782333-gefcgkdul0m4mh1vjnj02r4ins2bnac5.apps.googleusercontent.com',
    iosClientId: '967804782333-ig91rmrihju51ho0romdav3jpbu1jdg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.donys',
  );
}
